imports:
  - path: preset-mpc-org.jinja

resources:
  - name: iam
    type: preset-mpc-org.jinja
    properties:
      presetServiceAccount: 'terraform-automation@production-438252.iam.gserviceaccount.com'
      MPCServiceAccountId: "mpc-service-account"
      MPCAdminRoleId: "PresetMPCAdmin"
